USE hw7;

CREATE TABLE logging
(
 id INT AUTO_INCREMENT PRIMARY KEY,
 time TIMESTAMP,
 table_name VARCHAR(20),
 action SET('INSERT', 'UPDATE', 'DELETE'),
 user VARCHAR(20)
);

DELIMITER $
CREATE TRIGGER movie_logging_insert
 AFTER INSERT
 ON Movies
 FOR EACH ROW
 BEGIN
  INSERT INTO logging VALUES(NULL, NULL, 'Movies', 'INSERT', (SELECT CURRENT_USER()));
 END $
DELIMITER ;

DELIMITER $
CREATE TRIGGER movie_logging_update
 AFTER UPDATE
 ON Movies
 FOR EACH ROW
 BEGIN
  INSERT INTO logging VALUES(NULL, NULL, 'Movies', 'UPDATE', (SELECT CURRENT_USER()));
 END $
DELIMITER ;

DELIMITER $
CREATE TRIGGER movie_logging_delete
 AFTER DELETE
 ON Movies
 FOR EACH ROW
 BEGIN
  INSERT INTO logging VALUES(NULL, NULL, 'Movies', 'DELETE', (SELECT CURRENT_USER()));
 END $
DELIMITER ;

